# Generated by Django 3.0 on 2020-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admincontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FILES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='alt.png', upload_to='allfiles/')),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('cate', models.CharField(max_length=1000)),
                ('filesize', models.CharField(max_length=200)),
                ('filetype', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=1000)),
            ],
        ),
    ]
