# Generated by Django 3.0 on 2020-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admincontrol', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=10000)),
                ('des', models.TextField(max_length=1000000)),
                ('figure', models.TextField(max_length=1000000)),
            ],
        ),
    ]
