# Generated by Django 3.0 on 2021-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admincontrol', '0003_visualizeddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='alt.jpeg', upload_to='UserDataFiles/')),
                ('about', models.CharField(max_length=10000)),
            ],
        ),
    ]
