# Generated by Django 3.0 on 2021-05-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admincontrol', '0004_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userid',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='about',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
